name: DevOps CI/CD Pipeline

# Le pipeline se déclenche à chaque push sur la branche main
on:
  push:
    branches: [ "main" ]

jobs:
  build-test-publish:
    runs-on: ubuntu-latest

    steps:
    # 1. Récupération du code source
    - name: Checkout du code
      uses: actions/checkout@v4

    # 2. Préparation de l'environnement de test Python
    - name: Configurer Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Installer les dépendances de test
      run: pip install requests

    # 3. Création du fichier .env pour la CI
    - name: Créer le fichier d'environnement
      run: |
        echo "APP_PORT=8080" > .env
        echo "PROXY_PORT=80" >> .env
        echo "IMAGE_PATH=./images" >> .env
        echo "TEMP_PATH=./static/temp" >> .env

    # 4. Lancement de la stack (comme en local)
    - name: Démarrer l'infrastructure
      run: docker compose up -d --build

    # 5. Attente du Healthcheck
    - name: Attente du démarrage de l'API (Healthcheck)
      run: sleep 20 # On laisse le temps à l'API de s'initialiser

    # 6. Exécution des tests d'intégration
    - name: Lancer les tests
      run: python tests/test_stack.py

    # 7. Connexion à Docker Hub (Seulement si les tests passent !)
    - name: Connexion à Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 8. Publication de l'API avec Tag dynamique (SHA du commit)
    - name: Build & Push API Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.api
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/pixel-api:${{ github.sha }}
          ${{ secrets.DOCKER_USERNAME }}/pixel-api:latest

    # 9. Publication du Worker avec Tag dynamique
    - name: Build & Push Worker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.worker
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/pixel-worker:${{ github.sha }}
          ${{ secrets.DOCKER_USERNAME }}/pixel-worker:latest